name: backend-local
services:
  backend-postgres-db:
    image: postgres:18-alpine
    container_name: backend-postgres-db
    env_file:
      - .env.local
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - backend-network
    volumes:
      - backend_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend-service:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: backend-service
    env_file:
      - .env.local
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    networks:
      - backend-network
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - backend-postgres-db

volumes:
  backend_postgres_data:

networks:
  backend-network:
    driver: bridge